### ISSUE TITLE
Subgraph query doesn't specify AB contracts

### ISSUE THREAD

**Issue by ghost** [mattdesl/artblocks-renderer#1]
The website's subgraph query is too ambiguous and doesn't specify AB contracts. For example, using 3000007 shows an error message of 'multiple tokens received in the console.

**Comment by lyaunzbe** [comment]
Should be able to mitigate this issue by specifying the AB contracts in the query as a filter. Example: 

```
{
  tokens(where: {tokenId: "0", contract_in: ["0x059edd72cd353df5106d2b9cc5ab83a52287ac3a", "0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270"]}) {
    id
    tokenId
  }
}
```

**Comment by jakerockland** [comment]
ccing myself here, in case I am able to carve out time to help contribute back here via a PR :)

**Comment by mattdesl** [comment]
Should be fixed in latest, also made the prelude support a `clickOnStart` flag, which is enabled when projectId is `'0'` (squiggles), this way we can now export animated squiggles.

Thanks for the fix!

![0](https://user-images.githubusercontent.com/1383811/153472179-69d8e017-4fb2-43bd-9ccd-aff9cd2a9f0f.gif)
